# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: CI

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['*']

jobs:
  Test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node-version:
          - 16.x
        os:
          - ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{matrix.node-version}}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Top Level Dependencies
        run: npm install

      - name: Install Dependencies
        working-directory: ./packages/generator
        run: npm install

      - name: Run Tests
        working-directory: ./packages/generator
        run: npm test

  Publish:
    runs-on: ubuntu-latest
    needs:
      - Test
    if: ${{ github.ref == 'refs/heads/main' }}
    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          registry-url: https://registry.npmjs.org

      - name: Install Top Level Dependencies
        run: npm install

      - name: Install Dependencies
        working-directory: ./packages/generator
        run: npm install

      - name: Publish to NPM
        working-directory: ./packages/generator
        run: npx semantic-release
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
